### ISSUE TITLE
Fingerprints assumptions will fail on custom builds

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#19]
If a user modifies a file in boot partition that is necessarily for a board variant or so, fingerprints will include the correct values which will let resinhup run normally.

Ex:
1. user needs a change in a dtb - this change is vital for his board variant
2. builds and runs
3. resinhup will overwrite the change

We currently don't check fingerprints in boot but even if we would they would succeed as they come from the custom build which is valid.

CC @petrosagg

**Comment by imrehg** [comment]
@agherzan this is now superseded, right?

* we don't check hashes on boot anyways, and overwrite stuff, and that's given as a default behaviour.
* the future solution is hostapps, probably?
* if they do actual custom builds, then could use `hostapp-update` to update with that anyways, and then nothing will actually broken (this needs some thinking, currently nothing documented around this, but should still invalidate the issue I guess)

**Comment by agherzan** [comment]
Yup. I agree. Closing.
