### ISSUE TITLE
Remote device never came back after update

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#23]
uuid: aeee03dcac436febdfa884a08effefa938a9afbe11c6f2efba63aa69917de7

andrea.rosci@fwr.it will provide us a SD dump to investigate offline

**Comment by agherzan** [comment]
Waiting for SD image to debug offline.

**Comment by willnewton** [comment]
This has been blocked ~9 months so closing as it is not likely to ever make progress.
