### ISSUE TITLE
Integrate resin uboot with beaglebone

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#55]
The resin uboot was only integrated with artik5. Integrate it with beaglebone too and test resinhup on this board.

**Comment by willnewton** [comment]
@agherzan has this been done?

**Comment by agherzan** [comment]
https://github.com/resin-os/resin-beaglebone/pull/74
https://github.com/resin-os/resin-beaglebone/pull/101

Cheers @willnewton
