### ISSUE TITLE
Make staging/production variables configurable as arguments

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#57]
Hard-coding all these values here is not scalable and we should make them flexible as arguments to resinhup:
Ref: https://github.com/resin-os/resinhup/blob/983efd2fe404d2d1413fa9f67e107798f1d4546a/conf/resinhup.conf#L64

**Comment by imrehg** [comment]
This is fixed now on resinhup 2.x->2.x where the update parameters are pulled in differently and not hard-coded. For 1.x->1.x it should be probably a `won't fix`. I'm closing this for now, but let me know if I'm missing anything.
