### ISSUE TITLE
restart resin supervisor if resinHUP fails but the system has not been modified yet

### ISSUE THREAD

**Issue by imrehg** [resin-os/resinhup#67]
It can happen, that resinHUP fails on a device, and if run in self-service mode, then the device is not manageable, as the supervisor is already shut down in the beginning. This can happen for example due to fingerprint errors, when the bailing out is before anything was modified.

Feedback needed / this is just an idea, though, as probably it's highly desirable for the users to talk to us if something like this happens, but in the same time, it would be good to not have the device in an inoperable state, while one of our agents come to reboot, for example.

**Comment by agherzan** [comment]
The current idea is: if something happened with the update process we want to take a look on it. If we restart the services, supervisor will cleanup the images and we will not be able to investigate as we would want to. Definitely the plan is to improve this but for now we don't touch soft bricked device to give support engineers a chance to take a look.

**Comment by imrehg** [comment]
In the currently up-to-date resinOS the supervisor is completely out of the picture for resinHUP, and a different docker daemon is used, so this is a non-issue anymore. For the other, earlier devices as it is said above: debugging is more important from our point of view than putting the device back to the fully-functioning case.
