### ISSUE TITLE
Fixup or workaround the BTRFS label set from within container

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#7]
BTRFS labeling fails from within a running container.

**Comment by Page-** [comment]
Do you have some info on the error?

**Comment by agherzan** [comment]
I will provide it as soon as I will replicate it.

**Comment by agherzan** [comment]
@Page- 
```
root@raspberrypi2:/# btrfs filesystem label /host/mnt/data-disk/ resin-data
ERROR: unable to set label Bad address
```

**Comment by agherzan** [comment]
Workaround will be implemented in run-resinhup.sh (meta-resin) which will run this component.
