### ISSUE TITLE
resinHUP proceeds in case of cache even if cache is not loaded fine

### ISSUE THREAD

**Issue by imrehg** [resin-os/resinhup#73]
Trying to hunt down a resinHUP issue, and was testing when the device has cache downloaded beforehand, but let's pretend that the cache is corrupted (I cut off the end of the file, so originally ~80 MB, and made it into a ~75MB file with `dd`).

Looks like even if error logged (good!), the script did not bail out on `docker load error`:
```
[000000378][LOG]Found cached image [resin/resinos:1.26.0-raspberrypi3]. Loading it...
Error response from daemon: Untar re-exec error: exit status 1: output: unexpected EOF
[000000423][LOG]Running resinhup for version 1.26.0 ...

```
... (and proceeds with the update, with the broken OS image)

**Comment by agherzan** [comment]
It did not proceed with a broken OS image @imrehg . What happened is that import and run downloaded a new image. Basically the cache was ignored.

**Comment by imrehg** [comment]
Rrrrrrrrright, @agherzan , wasn't clear from the logs (for me), tried it out and it's correct assessment....
